[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "splid-devkit"
authors = [{name = "ARCLab", email = "ai_challenge@mit.edu"}]
dynamic = ["version", "description"]
